### ISSUE TITLE
执行issh apps 报错

### ISSUE THREAD

**Issue by WymanY** [4ch12dy/issh#10]
在执行issh apps的时候,报错
![image](https://user-images.githubusercontent.com/11940805/79314043-d0b7fd80-7f33-11ea-89b8-e59d94c73ca2.png)
issh:338: bad substitution，
但是我在执行issh shell的时候可以正常进入shell

**Comment by 4ch12dy** [comment]
这个好像是zsh不支持某些特性导致的，自带的终端bash是没问题的。

**Comment by WymanY** [comment]
那谢谢，我准备不用这个功能了
