### ISSUE TITLE
名称中有空格或者中文时debug命令有问题

### ISSUE THREAD

**Issue by Rico358097990** [4ch12dy/issh#12]
![image](https://user-images.githubusercontent.com/16099174/80300683-67f14080-87d1-11ea-89d0-8aee36a7ee69.png)
![image](https://user-images.githubusercontent.com/16099174/80300698-81928800-87d1-11ea-8616-581cd8a6d815.png)

**Comment by 4ch12dy** [comment]
第一个问题：后面的app执行路径你得放到双引号之间
第二个问题是由于我最近换了函数实现有关，你更新到最新的xia0LLDB版本，已经修复了

**Comment by Rico358097990** [comment]
第一个我加了双引号还是不行
![image](https://user-images.githubusercontent.com/16099174/80670086-996f5200-8ad8-11ea-857f-ee23ad3f2098.png)

第二个问题更新了xia0LLDB后还是有问题
![image](https://user-images.githubusercontent.com/16099174/80669931-2d8ce980-8ad8-11ea-93d3-b1194e99a03c.png)
![image](https://user-images.githubusercontent.com/16099174/80670163-c7ed2d00-8ad8-11ea-8575-83a581bcd762.png)

**Comment by 4ch12dy** [comment]
第一个问题：加双引号后还要对里面的空格进行转义，比如你这里的就是
`"/var/xxx/Instant\ Air\ Quality.app/Instant\ Air\ Quality"`
第二个问题：这个问题是某些手机上获取的app路径包含/private导致，最新v.28已修复

**Comment by Rico358097990** [comment]
3q
