### ISSUE TITLE
issh dump 在升级完frida 到15版本后，无法使用

### ISSUE THREAD

**Issue by WymanY** [4ch12dy/issh#14]
如题:我手机上之前的frida 版本为14.x，但是今天手贱升级了下，发现issh dump -l 无法使用了。
搜过相关问题，说是frida 15版本做了不兼容14的改动。
执行 issh dump -l 一定卡死
![image](https://user-images.githubusercontent.com/11940805/135247273-a7538ca5-9e9e-45d9-b60a-387f6b1d9f62.png)

**Comment by Rico358097990** [comment]
一样的问题 @4ch12dy

**Comment by WymanY** [comment]
我这边解决了，我同样升级了电脑端的frida，跟手机端保持一致，可以运行了 @Rico358097990
