### ISSUE TITLE
依赖工具问题

### ISSUE THREAD

**Issue by geekonion** [4ch12dy/issh#3]
继续支持。
请问下cfgutil是私有的吗?没找到这个工具
另外，defaults没找到手机版的

**Comment by Rico358097990** [comment]
sh: defaults: command not found

**Comment by 4ch12dy** [comment]
在mac app store中搜索apple configurator 2下载安装，里面就有cfgutil这个命令行工具。后面关于对这个命令依赖的部分准备用其他方式替换掉。
defaults这个命令我用这边的三台设备（iOS9/10/12）好像越狱以后就有这个命令，应该有cydia的源里有这个命令，或者用其他plist处理的命令替换也行

**Comment by 4ch12dy** [comment]
在mac app store中搜索apple configurator 2下载安装，里面就有cfgutil这个命令行工具。后面关于对这个命令依赖的部分准备用其他方式替换掉。



> sh: defaults: command not found

defaults这个命令再[https://repo.chariz.io](https://repo.chariz.io)源中安装Cephei就有了

**Comment by geekonion** [comment]
谢谢
