### ISSUE TITLE
debugserver进程不退出问题

### ISSUE THREAD

**Issue by geekonion** [4ch12dy/issh#4]
执行issh debug -a xxx后，如果没有用lldb连接，直接终止掉脚本的话，debugserver会一直等待attach，不做处理的话，xxx这个程序再也启动不了了，不注意的话，会坑。

**Comment by 4ch12dy** [comment]
> 执行issh debug -a xxx后，如果没有用lldb连接，直接终止掉脚本的话，debugserver会一直等待attach，不做处理的话，xxx这个程序再也启动不了了，不注意的话，会坑。

每次执行issh debug -a xxx的时候如果debugserver进程存在的话会自动kill掉，所以你再执行一遍就可以了

**Comment by geekonion** [comment]
嗯嗯，这个我晓得，就是考虑有没有什么办法保证不出现这个问题。
