### ISSUE TITLE
issh debug -a xxx 一直输入很多密码

### ISSUE THREAD

**Issue by SeanChense** [4ch12dy/issh#5]
➜  issh git:(master) issh debug -a xxx
[I]:iproxy process for 2222 port alive, pid=16859
[I]:scp id_rsa.pub to connect iDevice [1/2]
root@localhost's password:
[I]:add id_rsa.pub to authorized_keys [2/2]
root@localhost's password:
[I]:++++++++++++++++++ Nice to Work :) +++++++++++++++++++++
root@localhost's password:
[I]:iOSRE dir exist
[I]:iproxy process for 1234 port alive, pid=16904
[I]:Run ps -e | grep debugserver | grep -v grep; [[ 0 == 0 ]] && (killall -9 debugserver 2> /dev/null)
root@localhost's password:
root@localhost's password:
[I]:/iOSRE/tools/debugserver file exist, Start debug...
[I]:Run /iOSRE/tools/debugserver 127.0.0.1:1234 -a xxx

到这一步之后就没了，好像终止了

**Comment by 4ch12dy** [comment]
> ➜ issh git:(master) issh debug -a xxx
> [I]:iproxy process for 2222 port alive, pid=16859
> [I]:scp id_rsa.pub to connect iDevice [1/2]
> root@localhost's password:
> [I]:add id_rsa.pub to authorized_keys [2/2]
> root@localhost's password:
> [I]:++++++++++++++++++ Nice to Work :) +++++++++++++++++++++
> root@localhost's password:
> [I]:iOSRE dir exist
> [I]:iproxy process for 1234 port alive, pid=16904
> [I]:Run ps -e | grep debugserver | grep -v grep; [[ 0 == 0 ]] && (killall -9 debugserver 2> /dev/null)
> root@localhost's password:
> root@localhost's password:
> [I]:/iOSRE/tools/debugserver file exist, Start debug...
> [I]:Run /iOSRE/tools/debugserver 127.0.0.1:1234 -a xxx
> 
> 到这一步之后就没了，好像终止了

看起来像你电脑的公钥id_rsa.pub没能写入手机的/var/root/.ssh/authorized_keys里面
一般这种有以下原因你可以检查一下：

- 电脑上是否存在~/.ssh/id_rsa.pub公钥文件，没有的话用ssh-keygen生成一下
- 手机磁盘是否满了导致不能写入文件
- 其他原因，你可以手动添加试试看下报错

**Comment by SeanChense** [comment]
输入密码的问题解决了。
手机上的 authorized_keys 文件没自动生成，生成了也拷不进去。手动写进去了搞定

**Comment by SeanChense** [comment]
nice work
