### ISSUE TITLE
iish debug 无法使用

### ISSUE THREAD

**Issue by WymanY** [4ch12dy/issh#7]
![image](https://user-images.githubusercontent.com/11940805/63755417-2e3a0400-c8e9-11e9-8b6b-2e4b09a692cf.png)

一直卡在这里不动，但是使用issh shell，可以登录到手机，不知道为什么这个一直卡着，如果需要补充什么信息，希望您告诉我！

这里登录到越狱手机上使用PS -A,发现有这个命令在执行。

![image](https://user-images.githubusercontent.com/11940805/63756984-e49ee880-c8eb-11e9-9f2f-10fd76ef9f28.png)

然后我这边连接lldb中断是使用您的xiaolldb，发现无论是使用**pcc**命令还是**process connect connect://127.0.0.1:1234**命令都是抱下面的错

![image](https://user-images.githubusercontent.com/11940805/63757127-2a5bb100-c8ec-11e9-9d21-723c976a1016.png)

**Comment by 4ch12dy** [comment]
卡着就说明是调试成功的，pcc连不上的话估计是建议重启iproxy进程
