### ISSUE TITLE
安装应用失败

### ISSUE THREAD

**Issue by oschanger** [4ch12dy/issh#9]
➜  issh git:(master) issh install /Users/iCOS/Documents/chenxu/monkey/高德地图-精准地图,导航出行必备_v8.75.1.ipa
Installing 'com.autonavi.amap'
 - CreatingStagingDirectory (5%)
 - ExtractingPackage (15%)
 - InspectingPackage (20%)
 - TakingInstallLock (20%)
 - PreflightingApplication (30%)
 - InstallingEmbeddedProfile (30%)
 - VerifyingApplication (40%)
 - Error occurred: ApplicationVerificationFailed

checkrain越狱，ios12 13都不行

**Comment by 4ch12dy** [comment]
看日志的话应该是重签的时候签名不对吧

**Comment by oschanger** [comment]
这个命令还要配置什么环境吗，dump出来的包也不行

**Comment by 4ch12dy** [comment]
dump出来的肯定不行，不需要环境。但得确保IPA包重签名是正确的

**Comment by oschanger** [comment]
emm
就是说这个命令不会自动签名？
